In [9]:
import pandas as pd
import os
from zipfile import ZipFile 
user_profile = os.environ['USERPROFILE']

In [10]:
path_zip = user_profile + r"\Downloads\moov.zip"

dfs = []
with ZipFile(path_zip) as z:
    # Lista todos os arquivos no ZIP
    for filename in z.namelist():
        # Verifica se é um arquivo CSV
        if filename.endswith('.csv'):
            with z.open(filename) as f:
                df = pd.read_csv(f, 
                                encoding='ISO-8859-1',
                                on_bad_lines='skip', 
                                delimiter=';',
                                decimal=',', 
                                thousands='.',  
                                low_memory=False)
                dfs.append(df)
df_estoque = pd.concat(dfs, ignore_index=True)

In [12]:
df_estoque.columns

Index(['NOME_FUNDO', 'DOC_FUNDO', 'NOME_ORIGINADOR', 'DOC_ORIGINADOR',
       'NOME_CEDENTE', 'DOC_CEDENTE', 'NOME_SACADO', 'DOC_SACADO',
       'TIPO_RECEBIVEL', 'VALOR_NOMINAL', 'VALOR_PRESENTE', 'VALOR_AQUISICAO',
       'VALOR_PDD', 'DATA_VENCIMENTO_AJUSTADA', 'DATA_EMISSAO',
       'DATA_AQUISICAO', 'NU_DOCUMENTO', 'SEU_NUMERO', 'TX_RECEBIVEL', 'PRAZO',
       'PRAZO_ATUAL', 'SITUACAO_RECEBIVEL', 'FAIXA_PDD',
       'DATA_VENCIMENTO_ORIGINAL', 'TAXA_CESSAO', 'COOBRIGACAO', 'DATA_FUNDO',
       'DATA_REFERENCIA', 'MORA', 'MULTA', 'TAXA_JUROS_VENCIDOS',
       'DATA_CARENCIA', 'TAXA_JUROS_INDEXADOR', 'TP_JUROS', 'DEFASAGEM',
       'NOME', 'VALOR_NOMINAL_IOF', 'NU_BANCO_CHEQUE', 'NU_AGENCIA_CHEQUE',
       'NU_CONTA_CHEQUE', 'CMC7_CHEQUE', 'CODIGO_ORIGEM', 'CODIGO_FINALIDADE',
       'ID_REGISTRO', 'FAIXA_PDD_GERAL', 'TIPO_PDD_GERAL', 'VALOR_PDD_GERAL'],
      dtype='object')

In [14]:
df_estoque[['VALOR_PRESENTE','VALOR_PDD','SITUACAO_RECEBIVEL','FAIXA_PDD']]

        VALOR_PRESENTE  VALOR_PDD SITUACAO_RECEBIVEL FAIXA_PDD
0                 8.90       8.84            Vencido         L
1                 8.90       8.84            Vencido         L
2                 8.90       8.84            Vencido         L
3                 5.94       5.90            Vencido         L
4                89.08      88.47            Vencido         L
...                ...        ...                ...       ...
515338           26.69       0.15           A vencer         B
515339           57.84       0.00           A vencer         A
515340           69.42       0.00           A vencer         A
515341            8.19       0.00           A vencer         A
515342           19.34       0.11           A vencer         B

[515343 rows x 4 columns]

In [15]:
df_pdd = df_estoque[['VALOR_PRESENTE','VALOR_PDD','SITUACAO_RECEBIVEL','FAIXA_PDD']]

In [27]:
atraso_vp = df_estoque[df_estoque['SITUACAO_RECEBIVEL'] == 'Vencido']['VALOR_PRESENTE'].sum()
pdd_sem_wop = df_estoque[df_estoque['FAIXA_PDD'] != 'WOP']['VALOR_PDD'].sum()
pdd_wop = df_estoque[df_estoque['FAIXA_PDD'] == 'WOP']['VALOR_PDD'].sum()
valor_presente = df_estoque['VALOR_PRESENTE'].sum()
total_pdd = df_estoque['VALOR_PDD'].sum()

In [32]:
df_pdd = pd.DataFrame({
    'Carteira Atraso': [atraso_vp],
    'PDD s/ WO': [pdd_sem_wop],
    'PDD / Carteira Atraso': [pdd_sem_wop / atraso_vp if atraso_vp != 0 else 0],
    'Write-Off (WO)': [pdd_wop],
    'Carteira VP': [valor_presente],
    'PDD Total': [total_pdd],
    'PDD / Carteira': [total_pdd / valor_presente if valor_presente != 0 else 0]
})

In [33]:
df_pdd

,Carteira Atraso,PDD s/ WO,PDD / Carteira Atraso,Write-Off (WO),Carteira VP,PDD Total,PDD / Carteira
0,14865783.22,3008790.05,0.202397,6210691.69,42352377.69,9219481.74,0.217685

In [26]:
df_estoque[df_estoque['FAIXA_PDD'] == 'WOP']['VALOR_PDD'].sum()

np.float64(6210691.69)

In [25]:
df_estoque[df_estoque['FAIXA_PDD'] != 'WOP']['VALOR_PDD'].sum()

np.float64(3008790.05)

In [24]:
df_estoque['FAIXA_PDD'].unique()

array(['L', 'G', 'WOP', 'E', 'B', 'A', 'K', 'C', 'D', 'F', 'J', 'I', 'H'],
      dtype=object)

In [16]:
atraso_vp = df_estoque[df_estoque['SITUACAO_RECEBIVEL'] == 'Vencido']['VALOR_PRESENTE'].sum()

        VALOR_PRESENTE  VALOR_PDD SITUACAO_RECEBIVEL FAIXA_PDD
0                 8.90       8.84            Vencido         L
1                 8.90       8.84            Vencido         L
2                 8.90       8.84            Vencido         L
3                 5.94       5.90            Vencido         L
4                89.08      88.47            Vencido         L
...                ...        ...                ...       ...
515338           26.69       0.15           A vencer         B
515339           57.84       0.00           A vencer         A
515340           69.42       0.00           A vencer         A
515341            8.19       0.00           A vencer         A
515342           19.34       0.11           A vencer         B

[515343 rows x 4 columns]